from __future__ import annotations

from sqlalchemy import Float, Integer, String
from sqlalchemy.orm import Mapped, mapped_column

from .database import Base


class HouseListing(Base):
    __tablename__ = "house_listings"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    house_id: Mapped[str | None] = mapped_column(String(80), index=True)
    source: Mapped[str | None] = mapped_column(String(40))
    title: Mapped[str | None] = mapped_column(String(200))
    district: Mapped[str] = mapped_column(String(32), index=True)
    street: Mapped[str | None] = mapped_column(String(64), index=True)
    community_name: Mapped[str | None] = mapped_column(String(160), index=True)
    price: Mapped[float] = mapped_column(Float)
    unit_price: Mapped[float] = mapped_column(Float)
    area: Mapped[float | None] = mapped_column(Float)
    room_count: Mapped[float | None] = mapped_column(Float)
    hall_count: Mapped[float | None] = mapped_column(Float)
    toilet_count: Mapped[float | None] = mapped_column(Float)
    year_built: Mapped[float | None] = mapped_column(Float)
    total_floors: Mapped[float | None] = mapped_column(Float)
    community_households: Mapped[float | None] = mapped_column(Float)
    property_fee: Mapped[float | None] = mapped_column(Float)
    greening_rate: Mapped[float | None] = mapped_column(Float)
    community_avg_price: Mapped[float | None] = mapped_column(Float)
    renovation: Mapped[str | None] = mapped_column(String(80))
    floor_location: Mapped[str | None] = mapped_column(String(80))
    property_type: Mapped[str | None] = mapped_column(String(80))
    property_right: Mapped[str | None] = mapped_column(String(80))
    property_years: Mapped[str | None] = mapped_column(String(80))
    certificate_age: Mapped[str | None] = mapped_column(String(80))
    faces_south: Mapped[int | None] = mapped_column(Integer)
    faces_north_south: Mapped[int | None] = mapped_column(Integer)
    near_subway_text_flag: Mapped[int | None] = mapped_column(Integer)
    parking_text_flag: Mapped[int | None] = mapped_column(Integer)
    square_layout_text_flag: Mapped[int | None] = mapped_column(Integer)
    many_followers_text_flag: Mapped[int | None] = mapped_column(Integer)
    has_elevator_text_flag: Mapped[int | None] = mapped_column(Integer)
    wgs84_lng: Mapped[float] = mapped_column(Float)
    wgs84_lat: Mapped[float] = mapped_column(Float)
    gcj02_lng: Mapped[float] = mapped_column(Float)
    gcj02_lat: Mapped[float] = mapped_column(Float)


class PoiPoint(Base):
    __tablename__ = "poi_points"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    uid: Mapped[str | None] = mapped_column(String(96), index=True)
    name: Mapped[str] = mapped_column(String(160))
    category: Mapped[str] = mapped_column(String(24), index=True)
    source: Mapped[str] = mapped_column(String(64), index=True)
    district: Mapped[str] = mapped_column(String(32), index=True)
    street: Mapped[str | None] = mapped_column(String(64), index=True)
    tag: Mapped[str | None] = mapped_column(String(160))
    poi_subtype: Mapped[str | None] = mapped_column(String(48), index=True)
    service_role: Mapped[str | None] = mapped_column(String(48), index=True)
    life_circle_tier: Mapped[int | None] = mapped_column(Integer, index=True)
    is_life_service: Mapped[int] = mapped_column(Integer, index=True)
    supply_weight: Mapped[float] = mapped_column(Float)
    exclude_reason: Mapped[str | None] = mapped_column(String(120))
    wgs84_lng: Mapped[float | None] = mapped_column(Float)
    wgs84_lat: Mapped[float | None] = mapped_column(Float)
    gcj02_lng: Mapped[float] = mapped_column(Float)
    gcj02_lat: Mapped[float] = mapped_column(Float)


class DistrictMetric(Base):
    __tablename__ = "district_metrics"

    district: Mapped[str] = mapped_column(String(32), primary_key=True)
    avg_price: Mapped[float] = mapped_column(Float)
    avg_total_price: Mapped[float] = mapped_column(Float)
    house_count: Mapped[int] = mapped_column(Integer)
    poi_total: Mapped[int] = mapped_column(Integer)
    recreation_count: Mapped[int] = mapped_column(Integer)
    company_count: Mapped[int] = mapped_column(Integer)
    residence_count: Mapped[int] = mapped_column(Integer)
    shopping_count: Mapped[int] = mapped_column(Integer)
    traffic_count: Mapped[int] = mapped_column(Integer)
    healthcare_count: Mapped[int] = mapped_column(Integer)
    business_activity: Mapped[float] = mapped_column(Float)
    activity_norm: Mapped[float] = mapped_column(Float)
    price_norm: Mapped[float] = mapped_column(Float)
    livability_score: Mapped[float] = mapped_column(Float, index=True)
    livability_score_display: Mapped[float | None] = mapped_column(Float)
    poi_diversity: Mapped[float] = mapped_column(Float)
    shopping_per_house: Mapped[float] = mapped_column(Float)
    traffic_per_house: Mapped[float] = mapped_column(Float)
    healthcare_per_house: Mapped[float] = mapped_column(Float)
    recreation_per_house: Mapped[float] = mapped_column(Float)
    company_per_house: Mapped[float] = mapped_column(Float)
    cost_pressure: Mapped[float] = mapped_column(Float)
    affordability_score: Mapped[float] = mapped_column(Float)
    affordability_score_display: Mapped[float | None] = mapped_column(Float)
    service_score: Mapped[float] = mapped_column(Float)
    service_score_display: Mapped[float | None] = mapped_column(Float)
    vitality_score: Mapped[float] = mapped_column(Float)
    vitality_score_display: Mapped[float | None] = mapped_column(Float)
    livability_score_v2: Mapped[float] = mapped_column(Float, index=True)
    livability_score_v2_display: Mapped[float | None] = mapped_column(Float)
    shopping_access: Mapped[float] = mapped_column(Float)
    traffic_access: Mapped[float] = mapped_column(Float)
    healthcare_access: Mapped[float] = mapped_column(Float)
    recreation_access: Mapped[float] = mapped_column(Float)
    company_access: Mapped[float] = mapped_column(Float)
    nearest_traffic_distance: Mapped[float | None] = mapped_column(Float)
    nearest_healthcare_distance: Mapped[float | None] = mapped_column(Float)
    access_score: Mapped[float] = mapped_column(Float)
    access_score_display: Mapped[float | None] = mapped_column(Float)
    value_score: Mapped[float] = mapped_column(Float, index=True)
    value_score_display: Mapped[float | None] = mapped_column(Float)
    shopping_e2sfca_access: Mapped[float] = mapped_column(Float)
    traffic_e2sfca_access: Mapped[float] = mapped_column(Float)
    healthcare_e2sfca_access: Mapped[float] = mapped_column(Float)
    recreation_e2sfca_access: Mapped[float] = mapped_column(Float)
    company_e2sfca_access: Mapped[float] = mapped_column(Float)
    e2sfca_access_score: Mapped[float] = mapped_column(Float)
    e2sfca_access_score_display: Mapped[float | None] = mapped_column(Float)
    e2sfca_value_score: Mapped[float] = mapped_column(Float)
    e2sfca_value_score_display: Mapped[float | None] = mapped_column(Float)
    sample_reliability_score: Mapped[float] = mapped_column(Float)
    calibrated_score: Mapped[float] = mapped_column(Float, index=True)
    calibrated_score_display: Mapped[float | None] = mapped_column(Float)
    life_circle_5min_score: Mapped[float] = mapped_column(Float)
    life_circle_5min_score_display: Mapped[float | None] = mapped_column(Float)
    life_circle_10min_score: Mapped[float] = mapped_column(Float)
    life_circle_10min_score_display: Mapped[float | None] = mapped_column(Float)
    life_circle_15min_score: Mapped[float] = mapped_column(Float)
    life_circle_15min_score_display: Mapped[float | None] = mapped_column(Float)
    life_circle_score: Mapped[float] = mapped_column(Float, index=True)
    life_circle_score_display: Mapped[float | None] = mapped_column(Float)
    life_circle_5min_coverage: Mapped[float] = mapped_column(Float)
    life_circle_10min_coverage: Mapped[float] = mapped_column(Float)
    life_circle_15min_coverage: Mapped[float] = mapped_column(Float)
    calibrated_score_life_circle: Mapped[float] = mapped_column(Float, index=True)
    calibrated_score_life_circle_display: Mapped[float | None] = mapped_column(Float)
    center_lng: Mapped[float | None] = mapped_column(Float)
    center_lat: Mapped[float | None] = mapped_column(Float)


class StreetMetric(Base):
    __tablename__ = "street_metrics"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    district: Mapped[str] = mapped_column(String(32), index=True)
    street: Mapped[str] = mapped_column(String(64), index=True)
    avg_price: Mapped[float] = mapped_column(Float)
    avg_total_price: Mapped[float] = mapped_column(Float)
    house_count: Mapped[int] = mapped_column(Integer)
    poi_total: Mapped[int] = mapped_column(Integer)
    recreation_count: Mapped[int] = mapped_column(Integer)
    company_count: Mapped[int] = mapped_column(Integer)
    residence_count: Mapped[int] = mapped_column(Integer)
    shopping_count: Mapped[int] = mapped_column(Integer)
    traffic_count: Mapped[int] = mapped_column(Integer)
    healthcare_count: Mapped[int] = mapped_column(Integer)
    business_activity: Mapped[float] = mapped_column(Float)
    activity_norm: Mapped[float] = mapped_column(Float)
    price_norm: Mapped[float] = mapped_column(Float)
    livability_score: Mapped[float] = mapped_column(Float, index=True)
    livability_score_display: Mapped[float | None] = mapped_column(Float)
    poi_diversity: Mapped[float] = mapped_column(Float)
    shopping_per_house: Mapped[float] = mapped_column(Float)
    traffic_per_house: Mapped[float] = mapped_column(Float)
    healthcare_per_house: Mapped[float] = mapped_column(Float)
    recreation_per_house: Mapped[float] = mapped_column(Float)
    company_per_house: Mapped[float] = mapped_column(Float)
    cost_pressure: Mapped[float] = mapped_column(Float)
    affordability_score: Mapped[float] = mapped_column(Float)
    affordability_score_display: Mapped[float | None] = mapped_column(Float)
    service_score: Mapped[float] = mapped_column(Float)
    service_score_display: Mapped[float | None] = mapped_column(Float)
    vitality_score: Mapped[float] = mapped_column(Float)
    vitality_score_display: Mapped[float | None] = mapped_column(Float)
    livability_score_v2: Mapped[float] = mapped_column(Float, index=True)
    livability_score_v2_display: Mapped[float | None] = mapped_column(Float)
    shopping_access: Mapped[float] = mapped_column(Float)
    traffic_access: Mapped[float] = mapped_column(Float)
    healthcare_access: Mapped[float] = mapped_column(Float)
    recreation_access: Mapped[float] = mapped_column(Float)
    company_access: Mapped[float] = mapped_column(Float)
    nearest_traffic_distance: Mapped[float | None] = mapped_column(Float)
    nearest_healthcare_distance: Mapped[float | None] = mapped_column(Float)
    access_score: Mapped[float] = mapped_column(Float)
    access_score_display: Mapped[float | None] = mapped_column(Float)
    value_score: Mapped[float] = mapped_column(Float, index=True)
    value_score_display: Mapped[float | None] = mapped_column(Float)
    shopping_e2sfca_access: Mapped[float] = mapped_column(Float)
    traffic_e2sfca_access: Mapped[float] = mapped_column(Float)
    healthcare_e2sfca_access: Mapped[float] = mapped_column(Float)
    recreation_e2sfca_access: Mapped[float] = mapped_column(Float)
    company_e2sfca_access: Mapped[float] = mapped_column(Float)
    e2sfca_access_score: Mapped[float] = mapped_column(Float)
    e2sfca_access_score_display: Mapped[float | None] = mapped_column(Float)
    e2sfca_value_score: Mapped[float] = mapped_column(Float)
    e2sfca_value_score_display: Mapped[float | None] = mapped_column(Float)
    sample_reliability_score: Mapped[float] = mapped_column(Float)
    calibrated_score: Mapped[float] = mapped_column(Float, index=True)
    calibrated_score_display: Mapped[float | None] = mapped_column(Float)
    life_circle_5min_score: Mapped[float] = mapped_column(Float)
    life_circle_5min_score_display: Mapped[float | None] = mapped_column(Float)
    life_circle_10min_score: Mapped[float] = mapped_column(Float)
    life_circle_10min_score_display: Mapped[float | None] = mapped_column(Float)
    life_circle_15min_score: Mapped[float] = mapped_column(Float)
    life_circle_15min_score_display: Mapped[float | None] = mapped_column(Float)
    life_circle_score: Mapped[float] = mapped_column(Float, index=True)
    life_circle_score_display: Mapped[float | None] = mapped_column(Float)
    life_circle_5min_coverage: Mapped[float] = mapped_column(Float)
    life_circle_10min_coverage: Mapped[float] = mapped_column(Float)
    life_circle_15min_coverage: Mapped[float] = mapped_column(Float)
    calibrated_score_life_circle: Mapped[float] = mapped_column(Float, index=True)
    calibrated_score_life_circle_display: Mapped[float | None] = mapped_column(Float)
    center_lng: Mapped[float | None] = mapped_column(Float)
    center_lat: Mapped[float | None] = mapped_column(Float)


class PoiCategoryMetric(Base):
    __tablename__ = "poi_category_metrics"

    category: Mapped[str] = mapped_column(String(24), primary_key=True)
    count: Mapped[int] = mapped_column(Integer)
